<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="111235" started-at="2021-03-23T13:52:38Z" finished-at="2021-03-23T13:54:29Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="111235" started-at="2021-03-23T13:52:38Z" finished-at="2021-03-23T13:54:29Z">
      <class name="crmframework.crmAutomation.PeoplePageTest">
        <test-method status="PASS" signature="initialize()[pri:0, instance:crmframework.crmAutomation.PeoplePageTest@d8355a8]" name="initialize" is-config="true" duration-ms="2694" started-at="2021-03-23T19:22:38Z" finished-at="2021-03-23T19:22:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="TS001_VerifyHomePageTest()[pri:0, instance:crmframework.crmAutomation.PeoplePageTest@d8355a8]" name="TS001_VerifyHomePageTest" duration-ms="94153" started-at="2021-03-23T19:22:41Z" finished-at="2021-03-23T19:24:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TS001_VerifyHomePageTest -->
        <test-method status="FAIL" signature="TS002_VerifyFullNameandEIHKeyFilterForPeople()[pri:0, instance:crmframework.crmAutomation.PeoplePageTest@d8355a8]" name="TS002_VerifyFullNameandEIHKeyFilterForPeople" duration-ms="14359" started-at="2021-03-23T19:24:15Z" finished-at="2021-03-23T19:24:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at crmframework.crmAutomation.PeoplePageTest.TS002_VerifyFullNameandEIHKeyFilterForPeople(PeoplePageTest.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TS002_VerifyFullNameandEIHKeyFilterForPeople -->
      </class> <!-- crmframework.crmAutomation.PeoplePageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
